### ISSUE TITLE
24h clock

### ISSUE THREAD

**Issue by miT-nib-hcI** [ChrisTitusTech/titus-awesome#10]
Im trying to get a 24h clock into the status bar. I found an option in the `top-panal.lua` for it but it only gifs me the date in the DD/MM/YYYY format. Can anyone tell me what to do?

**Comment by gramms** [comment]
use `local textclock = wibox.widget.textclock('<span font="Roboto Mono bold 9">%d.%m.%Y\n%H:%M</span>')`

**Comment by gramms** [comment]
use `local textclock = wibox.widget.textclock('<span font="Roboto Mono bold 9">%d.%m.%Y - %H:%M</span>')`
