### ISSUE TITLE
focus is not inside the terminal when you toggle the background terminal into foreground

### ISSUE THREAD

**Issue by c02y** [ChrisTitusTech/titus-awesome#16]

**Comment by nilsvandensteen** [comment]
If you mean the drop-down terminal, you can fix this by modifying the `awesome/module/quake-terminal.lua` file
```lua
function open_quake()
  quake_client.hidden = false
  _G.client.focus = quake_client
end
```

**Comment by c02y** [comment]
Sorry, I'll just close this:
1. I don't remember the details anymore
2. I don't use awesome anymore, just tried it, never really use it.
3. I don't use Quake terminal from the first beginning
